import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'appbar_trailing.dart';
import 'drawer.dart';

class SettingsPage extends StatelessWidget {
  static const String route = '/SettingsPage';
  final String title = 'Settings';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(this.title),
        actions: [AppbarTrailingInfo()],
      ),
      drawer: NavDrawer(SettingsPage.route),
      body: ListView(
        children: [
          // This could also be a CheckboxListTile
          SwitchListTile(
            title: Text(
                'Subtract smaller particle size ranges from the bigger ones?'),
            subtitle: Text(
                '''Show particle sizes in separate ranges instead of beginning all ranges from 0.3µm.
This applies to the Mass Concentration and Number Concentration graphs
Example:  2.5-4.0µm, instead of 0.3-4.0µm.
This output is generated by subtracting the smaller particle size ranges from the bigger ones.
'''),
            value: true,
            onChanged: (value) => null,
          ),
        ],
      ),
    );
  }
}
